### ISSUE TITLE
Bota eklenebilecek ekstra özellikler

### ISSUE THREAD

**Issue by mrtozkn** [MehmetYukselSekeroglu/SiberGuvenlikTurkeyBot#1]
Kanka bunların birazı bile bota eklenebilirse güzel olur.

### 1. Whois Sorgusu
- Komut: /whois <domain>
- Açıklama: Bir domain adı hakkında whois sorgusu yapar ve kayıtlı bilgileri getirir.

### 2. DNS Sorgusu
- Komut: /dns <domain>
- Açıklama: Bir domainin DNS bilgilerini getirir (A, MX, CNAME, NS gibi kayıtlar).

### 3. Reverse IP Lookup (Ters IP Sorgusu)
- Komut: /reverseip <ip_adresi>
- Açıklama: Bir IP adresine bağlı tüm domain isimlerini listeler.

### 4. Subdomain Keşfi
- Komut: /subdomain <domain>
- Açıklama: Bir domain için bağlı subdomain’leri keşfeder.

### 5. Port Tarayıcı
- Komut: /portscan <ip_adresi> <port_aralığı>
- Açıklama: Bir IP adresi üzerinde açık portları tarar ve bulur.

### 6. SSL Sertifika Bilgisi
- Komut: /ssl <domain>
- Açıklama: Bir domainin SSL sertifikası hakkında bilgileri getirir (geçerlilik süresi, sertifika sağlayıcısı, vb.).

### 7. Geolocation (IP Konum Tespiti)
- Komut: /geoip <ip_adresi>
- Açıklama: Bir IP adresine göre hedefin tahmini coğrafi konumunu verir.

### 8. Malware Hash Taraması
- Komut: /malhash <hash>
- Açıklama: Bir dosya veya string hash'ine göre malware veri tabanından tarama yapar.

### 9. Email Validasyon
- Komut: /emailvalid <email_adresi>
- Açıklama: Girilen bir e-posta adresinin geçerliliğini kontrol eder ve MX kayıtlarını doğrular.

### 10. Password Strength Checker (Şifre Gücü Kontrolü)
- Komut: /passcheck <şifre>
- Açıklama: Girilen şifrenin zayıf ya da güçlü olduğunu kontrol eder.

### 11. Dark Web Arama
- Komut: /darkweb <keyword>
- Açıklama: Girilen anahtar kelimenin dark web üzerinde bulunup bulunmadığını kontrol eder.

### 12. URL Shortener (URL Kısaltma)
- Komut: /shorten <url>
- Açıklama: Uzun bir URL'yi kısa bir hale getirir.

### 13. SHA/MD5 Hash Hesaplama
- Komut: /hash <metin>
- Açıklama: Girilen metnin SHA256, MD5 gibi hash'lerini hesaplar.

### 14. Base64 Encode/Decode
- Komut: /base64encode <metin> ve /base64decode <metin>
- Açıklama: Metni base64 formatına çevirir veya base64 formatındaki metni çözer.

### 15. Pwned Password Checker (Şifre Sızıntı Kontrolü)
- Komut: /pwned <şifre>
- Açıklama: Girilen şifrenin veri sızıntılarında yer alıp almadığını kontrol eder.

### 16. Metadata Extractor (Dosya Meta Verisi Çıkarıcı)
- Komut: /metadata <dosya>
- Açıklama: Bir dosya yüklenip içindeki meta verileri (EXIF, PDF metadata vb.) analiz eder.

### 17. Binary to Text ve Text to Binary
- Komut: /bin2text <binary_kodu> ve /text2bin <metin>
- Açıklama: Binary formatındaki bir veriyi metne çevirir ya da metni binary formatına dönüştürür.

### 18. CIDR Dönüştürücü
- Komut: /cidrconvert <CIDR_notasyonu>
- Açıklama: CIDR notasyonunu IP aralığına çevirir.

### 19. HTTP Header Analizi
- Komut: /httpheaders <url>
- Açıklama: Girilen URL'nin HTTP header bilgilerini analiz eder (sunucu türü, güvenlik önlemleri, vb.).

### 20. IP Reputation (IP İtibar Kontrolü)
- Komut: /ipreputation <ip_adresi>
- Açıklama: Girilen IP adresinin kötü amaçlı faaliyetlerde kullanılıp kullanılmadığını ve itibarını kontrol eder.

**Comment by mikropsoft** [comment]
Çoğunu yaptıktan sonra daha fazla fikir buluruz kanka kolay gelsin.

**Comment by MehmetYukselSekeroglu** [comment]
> Kanka bunların birazı bile bota eklenebilirse güzel olur.
> 
> ### 1. Whois Sorgusu
> * Komut: /whois
> * Açıklama: Bir domain adı hakkında whois sorgusu yapar ve kayıtlı bilgileri getirir.
> 
> ### 2. DNS Sorgusu
> * Komut: /dns
> * Açıklama: Bir domainin DNS bilgilerini getirir (A, MX, CNAME, NS gibi kayıtlar).
> 
> ### 3. Reverse IP Lookup (Ters IP Sorgusu)
> * Komut: /reverseip <ip_adresi>
> * Açıklama: Bir IP adresine bağlı tüm domain isimlerini listeler.
> 
> ### 4. Subdomain Keşfi
> * Komut: /subdomain
> * Açıklama: Bir domain için bağlı subdomain’leri keşfeder.
> 
> ### 5. Port Tarayıcı
> * Komut: /portscan <ip_adresi> <port_aralığı>
> * Açıklama: Bir IP adresi üzerinde açık portları tarar ve bulur.
> 
> ### 6. SSL Sertifika Bilgisi
> * Komut: /ssl
> * Açıklama: Bir domainin SSL sertifikası hakkında bilgileri getirir (geçerlilik süresi, sertifika sağlayıcısı, vb.).
> 
> ### 7. Geolocation (IP Konum Tespiti)
> * Komut: /geoip <ip_adresi>
> * Açıklama: Bir IP adresine göre hedefin tahmini coğrafi konumunu verir.
> 
> ### 8. Malware Hash Taraması
> * Komut: /malhash
> * Açıklama: Bir dosya veya string hash'ine göre malware veri tabanından tarama yapar.
> 
> ### 9. Email Validasyon
> * Komut: /emailvalid <email_adresi>
> * Açıklama: Girilen bir e-posta adresinin geçerliliğini kontrol eder ve MX kayıtlarını doğrular.
> 
> ### 10. Password Strength Checker (Şifre Gücü Kontrolü)
> * Komut: /passcheck <şifre>
> * Açıklama: Girilen şifrenin zayıf ya da güçlü olduğunu kontrol eder.
> 
> ### 11. Dark Web Arama
> * Komut: /darkweb
> * Açıklama: Girilen anahtar kelimenin dark web üzerinde bulunup bulunmadığını kontrol eder.
> 
> ### 12. URL Shortener (URL Kısaltma)
> * Komut: /shorten
> * Açıklama: Uzun bir URL'yi kısa bir hale getirir.
> 
> ### 13. SHA/MD5 Hash Hesaplama
> * Komut: /hash
> * Açıklama: Girilen metnin SHA256, MD5 gibi hash'lerini hesaplar.
> 
> ### 14. Base64 Encode/Decode
> * Komut: /base64encode  ve /base64decode
> * Açıklama: Metni base64 formatına çevirir veya base64 formatındaki metni çözer.
> 
> ### 15. Pwned Password Checker (Şifre Sızıntı Kontrolü)
> * Komut: /pwned <şifre>
> * Açıklama: Girilen şifrenin veri sızıntılarında yer alıp almadığını kontrol eder.
> 
> ### 16. Metadata Extractor (Dosya Meta Verisi Çıkarıcı)
> * Komut: /metadata
> * Açıklama: Bir dosya yüklenip içindeki meta verileri (EXIF, PDF metadata vb.) analiz eder.
> 
> ### 17. Binary to Text ve Text to Binary
> * Komut: /bin2text <binary_kodu> ve /text2bin
> * Açıklama: Binary formatındaki bir veriyi metne çevirir ya da metni binary formatına dönüştürür.
> 
> ### 18. CIDR Dönüştürücü
> * Komut: /cidrconvert <CIDR_notasyonu>
> * Açıklama: CIDR notasyonunu IP aralığına çevirir.
> 
> ### 19. HTTP Header Analizi
> * Komut: /httpheaders
> * Açıklama: Girilen URL'nin HTTP header bilgilerini analiz eder (sunucu türü, güvenlik önlemleri, vb.).
> 
> ### 20. IP Reputation (IP İtibar Kontrolü)
> * Komut: /ipreputation <ip_adresi>
> * Açıklama: Girilen IP adresinin kötü amaçlı faaliyetlerde kullanılıp kullanılmadığını ve itibarını kontrol eder.

Tamamdır eklenecekler listesine alıyorum bunları

**Comment by mikropsoft** [comment]
> > Kanka bunların birazı bile bota eklenebilirse güzel olur.
> > ### 1. Whois Sorgusu
> > 
> > * Komut: /whois
> > * Açıklama: Bir domain adı hakkında whois sorgusu yapar ve kayıtlı bilgileri getirir.
> > 
> > ### 2. DNS Sorgusu
> > 
> > * Komut: /dns
> > * Açıklama: Bir domainin DNS bilgilerini getirir (A, MX, CNAME, NS gibi kayıtlar).
> > 
> > ### 3. Reverse IP Lookup (Ters IP Sorgusu)
> > 
> > * Komut: /reverseip <ip_adresi>
> > * Açıklama: Bir IP adresine bağlı tüm domain isimlerini listeler.
> > 
> > ### 4. Subdomain Keşfi
> > 
> > * Komut: /subdomain
> > * Açıklama: Bir domain için bağlı subdomain’leri keşfeder.
> > 
> > ### 5. Port Tarayıcı
> > 
> > * Komut: /portscan <ip_adresi> <port_aralığı>
> > * Açıklama: Bir IP adresi üzerinde açık portları tarar ve bulur.
> > 
> > ### 6. SSL Sertifika Bilgisi
> > 
> > * Komut: /ssl
> > * Açıklama: Bir domainin SSL sertifikası hakkında bilgileri getirir (geçerlilik süresi, sertifika sağlayıcısı, vb.).
> > 
> > ### 7. Geolocation (IP Konum Tespiti)
> > 
> > * Komut: /geoip <ip_adresi>
> > * Açıklama: Bir IP adresine göre hedefin tahmini coğrafi konumunu verir.
> > 
> > ### 8. Malware Hash Taraması
> > 
> > * Komut: /malhash
> > * Açıklama: Bir dosya veya string hash'ine göre malware veri tabanından tarama yapar.
> > 
> > ### 9. Email Validasyon
> > 
> > * Komut: /emailvalid <email_adresi>
> > * Açıklama: Girilen bir e-posta adresinin geçerliliğini kontrol eder ve MX kayıtlarını doğrular.
> > 
> > ### 10. Password Strength Checker (Şifre Gücü Kontrolü)
> > 
> > * Komut: /passcheck <şifre>
> > * Açıklama: Girilen şifrenin zayıf ya da güçlü olduğunu kontrol eder.
> > 
> > ### 11. Dark Web Arama
> > 
> > * Komut: /darkweb
> > * Açıklama: Girilen anahtar kelimenin dark web üzerinde bulunup bulunmadığını kontrol eder.
> > 
> > ### 12. URL Shortener (URL Kısaltma)
> > 
> > * Komut: /shorten
> > * Açıklama: Uzun bir URL'yi kısa bir hale getirir.
> > 
> > ### 13. SHA/MD5 Hash Hesaplama
> > 
> > * Komut: /hash
> > * Açıklama: Girilen metnin SHA256, MD5 gibi hash'lerini hesaplar.
> > 
> > ### 14. Base64 Encode/Decode
> > 
> > * Komut: /base64encode  ve /base64decode
> > * Açıklama: Metni base64 formatına çevirir veya base64 formatındaki metni çözer.
> > 
> > ### 15. Pwned Password Checker (Şifre Sızıntı Kontrolü)
> > 
> > * Komut: /pwned <şifre>
> > * Açıklama: Girilen şifrenin veri sızıntılarında yer alıp almadığını kontrol eder.
> > 
> > ### 16. Metadata Extractor (Dosya Meta Verisi Çıkarıcı)
> > 
> > * Komut: /metadata
> > * Açıklama: Bir dosya yüklenip içindeki meta verileri (EXIF, PDF metadata vb.) analiz eder.
> > 
> > ### 17. Binary to Text ve Text to Binary
> > 
> > * Komut: /bin2text <binary_kodu> ve /text2bin
> > * Açıklama: Binary formatındaki bir veriyi metne çevirir ya da metni binary formatına dönüştürür.
> > 
> > ### 18. CIDR Dönüştürücü
> > 
> > * Komut: /cidrconvert <CIDR_notasyonu>
> > * Açıklama: CIDR notasyonunu IP aralığına çevirir.
> > 
> > ### 19. HTTP Header Analizi
> > 
> > * Komut: /httpheaders
> > * Açıklama: Girilen URL'nin HTTP header bilgilerini analiz eder (sunucu türü, güvenlik önlemleri, vb.).
> > 
> > ### 20. IP Reputation (IP İtibar Kontrolü)
> > 
> > * Komut: /ipreputation <ip_adresi>
> > * Açıklama: Girilen IP adresinin kötü amaçlı faaliyetlerde kullanılıp kullanılmadığını ve itibarını kontrol eder.
> 
> Tamamdır eklenecekler listesine alıyorum bunları

Eline sağlık kardeşim ama kodlar biraz dağınık olmuş, ufak tefek yazım hataları ve gereksiz boşluklar var. Bir ara el atarsan süper olur, Türkçemizi de bozmayalım, ne dersin? :)
